export default {
  at: '2023-02-26T16:31:38.311Z',
  products: [
    {
      description: 'cupidatat minim nisi ad',
      name: 'sint',
      price: 982.73,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'do Lorem do non',
      name: 'culpa',
      price: 1752.82,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'id ea ut magna',
      name: 'amet',
      price: 282.19,
      tmpProperty: 'undefined',
      activePromoId: 84,
    },
    {
      description: 'adipisicing nisi ut occaecat',
      name: 'velit',
      price: 587.19,
      tmpProperty: 'undefined',
      activePromoId: 84,
    },
    {
      description: 'veniam eiusmod eu nulla',
      name: 'anim',
      price: 830.7,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'voluptate labore consequat nostrud',
      name: 'aliquip',
      price: 1988.82,
      tmpProperty: 'undefined',
      activePromoId: 72,
    },
    {
      description: 'dolor nisi consequat irure',
      name: 'non',
      price: 1855.57,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'aliqua excepteur enim pariatur',
      name: 'ut',
      price: 1417.51,
      tmpProperty: 'undefined',
      activePromoId: 88,
    },
    {
      description: 'reprehenderit eiusmod culpa deserunt',
      name: 'sit',
      price: 1713.97,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'sint velit magna veniam',
      name: 'labore',
      price: 1472.8,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'ullamco nulla dolor aliquip',
      name: 'sit',
      price: 1228.76,
      tmpProperty: 'undefined',
      activePromoId: 15,
    },
    {
      description: 'ut amet nostrud anim',
      name: 'occaecat',
      price: 161.09,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'consectetur ipsum aute aliqua',
      name: 'officia',
      price: 1928.04,
      tmpProperty: 'undefined',
      activePromoId: 8,
    },
    {
      description: 'non sint enim aliqua',
      name: 'sunt',
      price: 392.91,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'enim et cupidatat laboris',
      name: 'deserunt',
      price: 986.27,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'commodo ullamco voluptate eu',
      name: 'aute',
      price: 1065.91,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'elit cillum irure nostrud',
      name: 'anim',
      price: 665.05,
      tmpProperty: 'undefined',
      activePromoId: 99,
    },
    {
      description: 'occaecat adipisicing elit reprehenderit',
      name: 'irure',
      price: 996.96,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'voluptate incididunt enim cupidatat',
      name: 'mollit',
      price: 123.4,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'cupidatat tempor incididunt aute',
      name: 'officia',
      price: 1348.05,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'excepteur do nulla magna',
      name: 'fugiat',
      price: 1057.89,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'aute cupidatat eu nostrud',
      name: 'et',
      price: 1136.15,
      tmpProperty: 'undefined',
      activePromoId: 46,
    },
    {
      description: 'nostrud qui irure culpa',
      name: 'sit',
      price: 315.26,
      tmpProperty: 'undefined',
      activePromoId: 30,
    },
    {
      description: 'tempor commodo ullamco exercitation',
      name: 'nisi',
      price: 1039.29,
      tmpProperty: 'undefined',
      activePromoId: 90,
    },
    {
      description: 'consequat cupidatat eu nisi',
      name: 'ad',
      price: 370.36,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'sint adipisicing consectetur deserunt',
      name: 'dolor',
      price: 1213.99,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'laborum officia officia consequat',
      name: 'fugiat',
      price: 1307.63,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'ex consequat in elit',
      name: 'occaecat',
      price: 815.44,
      tmpProperty: 'undefined',
      activePromoId: 43,
    },
    {
      description: 'non dolore exercitation irure',
      name: 'ea',
      price: 411.97,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'amet est labore eiusmod',
      name: 'occaecat',
      price: 1570.91,
      tmpProperty: 'undefined',
      activePromoId: 11,
    },
    {
      description: 'deserunt enim excepteur qui',
      name: 'duis',
      price: 994.13,
      tmpProperty: 'undefined',
      activePromoId: 70,
    },
    {
      description: 'consectetur officia ex sunt',
      name: 'excepteur',
      price: 999.59,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'ad irure nisi reprehenderit',
      name: 'pariatur',
      price: 1259.37,
      tmpProperty: 'undefined',
      activePromoId: 63,
    },
    {
      description: 'sint ut eu cupidatat',
      name: 'pariatur',
      price: 1461.48,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'anim sit ullamco aute',
      name: 'culpa',
      price: 1294.04,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'duis dolore nisi esse',
      name: 'deserunt',
      price: 644.97,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'id ex et sit',
      name: 'cupidatat',
      price: 1742.34,
      tmpProperty: 'undefined',
      activePromoId: 1,
    },
    {
      description: 'excepteur cillum laborum qui',
      name: 'aute',
      price: 1898.09,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'do aliqua consequat labore',
      name: 'eu',
      price: 1715.82,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'culpa tempor labore tempor',
      name: 'reprehenderit',
      price: 568.62,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'sunt amet eiusmod adipisicing',
      name: 'proident',
      price: 1652.09,
      tmpProperty: 'undefined',
      activePromoId: 96,
    },
    {
      description: 'Lorem enim aliquip et',
      name: 'non',
      price: 1005.53,
      tmpProperty: 'undefined',
      activePromoId: 47,
    },
    {
      description: 'officia do magna ea',
      name: 'est',
      price: 1421.41,
      tmpProperty: 'undefined',
      activePromoId: 13,
    },
    {
      description: 'aute id anim ad',
      name: 'dolor',
      price: 1093.37,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'eu ad adipisicing exercitation',
      name: 'id',
      price: 1870.46,
      tmpProperty: 'undefined',
      activePromoId: 38,
    },
    {
      description: 'veniam dolor ad exercitation',
      name: 'occaecat',
      price: 1212.36,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'ad eiusmod deserunt aliquip',
      name: 'cillum',
      price: 1512.34,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'aliquip dolore consectetur ullamco',
      name: 'culpa',
      price: 1989.15,
      tmpProperty: 'undefined',
      activePromoId: 1,
    },
    {
      description: 'id eu eu anim',
      name: 'id',
      price: 206.39,
      tmpProperty: 'undefined',
      activePromoId: 32,
    },
    {
      description: 'consectetur aute cillum id',
      name: 'ullamco',
      price: 879.74,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'anim in irure non',
      name: 'ad',
      price: 658.95,
      tmpProperty: 'undefined',
      activePromoId: 21,
    },
    {
      description: 'nulla nostrud tempor sit',
      name: 'ipsum',
      price: 1568.82,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'amet culpa aliqua sunt',
      name: 'deserunt',
      price: 1300.85,
      tmpProperty: 'undefined',
      activePromoId: 56,
    },
    {
      description: 'occaecat anim ex culpa',
      name: 'sunt',
      price: 1161.93,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'id exercitation reprehenderit aliqua',
      name: 'enim',
      price: 688.71,
      tmpProperty: 'undefined',
      activePromoId: 49,
    },
    {
      description: 'voluptate id exercitation ad',
      name: 'fugiat',
      price: 1178.07,
      tmpProperty: 'undefined',
      activePromoId: 19,
    },
    {
      description: 'amet exercitation occaecat ullamco',
      name: 'irure',
      price: 1120.68,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'elit Lorem incididunt occaecat',
      name: 'adipisicing',
      price: 778.89,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'laborum dolore excepteur deserunt',
      name: 'duis',
      price: 1125.59,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'magna in nisi sit',
      name: 'laboris',
      price: 274.9,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'anim proident elit culpa',
      name: 'proident',
      price: 1474.18,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'nisi esse dolor deserunt',
      name: 'nisi',
      price: 1497.2,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'qui quis culpa enim',
      name: 'minim',
      price: 438.36,
      tmpProperty: 'undefined',
      activePromoId: 17,
    },
    {
      description: 'eiusmod deserunt pariatur fugiat',
      name: 'cillum',
      price: 1014.54,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'quis reprehenderit nostrud aliquip',
      name: 'ullamco',
      price: 145.07,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'nisi laborum nostrud laboris',
      name: 'magna',
      price: 1380.24,
      tmpProperty: 'undefined',
      activePromoId: 55,
    },
    {
      description: 'cupidatat minim dolore ex',
      name: 'elit',
      price: 625.25,
      tmpProperty: 'undefined',
      activePromoId: 12,
    },
    {
      description: 'consequat voluptate tempor consectetur',
      name: 'consequat',
      price: 668.76,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'reprehenderit dolore nisi laborum',
      name: 'commodo',
      price: 1703.63,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'elit qui esse quis',
      name: 'irure',
      price: 782.78,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'officia anim aliqua ut',
      name: 'aliquip',
      price: 969.42,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'sint fugiat minim cupidatat',
      name: 'nulla',
      price: 713.9,
      tmpProperty: 'undefined',
      activePromoId: 3,
    },
    {
      description: 'fugiat irure do est',
      name: 'exercitation',
      price: 147.39,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'veniam mollit adipisicing elit',
      name: 'enim',
      price: 1563.49,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'in id commodo ullamco',
      name: 'qui',
      price: 361.1,
      tmpProperty: 'undefined',
      activePromoId: 43,
    },
    {
      description: 'sit ullamco proident aliqua',
      name: 'non',
      price: 1040.51,
      tmpProperty: 'undefined',
      activePromoId: 78,
    },
    {
      description: 'aliquip incididunt magna magna',
      name: 'aute',
      price: 177.61,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'Lorem Lorem adipisicing velit',
      name: 'nulla',
      price: 1336.84,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'velit do Lorem do',
      name: 'dolor',
      price: 1775.89,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'nisi magna voluptate Lorem',
      name: 'ex',
      price: 1264.61,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'deserunt magna tempor laborum',
      name: 'incididunt',
      price: 154.83,
      tmpProperty: 'undefined',
      activePromoId: 89,
    },
    {
      description: 'nulla enim nulla sint',
      name: 'enim',
      price: 1398.8,
      tmpProperty: 'undefined',
      activePromoId: 52,
    },
    {
      description: 'mollit fugiat ad tempor',
      name: 'et',
      price: 135.07,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'excepteur anim aliqua excepteur',
      name: 'nulla',
      price: 669.68,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'Lorem sit in occaecat',
      name: 'laborum',
      price: 161.27,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'excepteur labore labore voluptate',
      name: 'eu',
      price: 1638.95,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'non tempor et elit',
      name: 'consequat',
      price: 1335.84,
      tmpProperty: 'undefined',
      activePromoId: 50,
    },
    {
      description: 'aliqua minim culpa sit',
      name: 'tempor',
      price: 585.46,
      tmpProperty: 'undefined',
      activePromoId: 71,
    },
    {
      description: 'mollit reprehenderit dolor fugiat',
      name: 'ex',
      price: 1525.94,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'est anim ipsum ullamco',
      name: 'reprehenderit',
      price: 1664.38,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'et do officia aliqua',
      name: 'id',
      price: 131.74,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'enim sit ut elit',
      name: 'sunt',
      price: 1324.5,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'amet et id laboris',
      name: 'culpa',
      price: 847.87,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'veniam cillum proident cupidatat',
      name: 'consequat',
      price: 1148.78,
      tmpProperty: 'undefined',
      activePromoId: 66,
    },
    {
      description: 'quis consectetur mollit est',
      name: 'laboris',
      price: 476.9,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'ut ullamco do eu',
      name: 'non',
      price: 293.99,
      tmpProperty: 'undefined',
      activePromoId: 77,
    },
    {
      description: 'duis minim ipsum amet',
      name: 'reprehenderit',
      price: 1601.47,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'adipisicing commodo laboris proident',
      name: 'ut',
      price: 1435.96,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'voluptate commodo consectetur eu',
      name: 'ipsum',
      price: 363.73,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
    {
      description: 'aute amet aute culpa',
      name: 'ex',
      price: 1643.21,
      tmpProperty: 'undefined',
      activePromoId: null,
    },
  ],
}
